"""add operator to routes

Revision ID: ac61dd81f6ea
Revises: febbeb92ab7d
Create Date: 2026-04-22 09:21:45.359774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac61dd81f6ea'
down_revision: Union[str, Sequence[str], None] = 'febbeb92ab7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routes', sa.Column('operator', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'operator')
    # ### end Alembic commands ###
