"""initial_schema

Revision ID: febbeb92ab7d
Revises: 
Create Date: 2026-04-21 16:39:51.453048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'febbeb92ab7d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('long_name', sa.String(length=255), nullable=False),
    sa.Column('terminal_primary', sa.String(length=255), nullable=True),
    sa.Column('terminal_secondary', sa.String(length=255), nullable=True),
    sa.Column('modal', sa.Enum('BUS', 'METRO', 'TRAIN', name='transportmodal', native_enum=False, length=20), nullable=False),
    sa.Column('color', sa.String(length=6), server_default='#0066CC', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_external_id'), 'routes', ['external_id'], unique=True)
    op.create_index(op.f('ix_routes_modal'), 'routes', ['modal'], unique=False)
    op.create_table('stops',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('modal', sa.Enum('BUS', 'METRO', 'TRAIN', name='transportmodal', native_enum=False, length=20), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('has_shelter', sa.Boolean(), nullable=True),
    sa.Column('is_accessible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stops_external_id'), 'stops', ['external_id'], unique=True)
    op.create_index(op.f('ix_stops_modal'), 'stops', ['modal'], unique=False)
    op.create_table('favorite_routes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('notify_delays', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notify_changes', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'route_id', name='uq_user_route_favorite')
    )
    op.create_index(op.f('ix_favorite_routes_created_at'), 'favorite_routes', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorite_routes_route_id'), 'favorite_routes', ['route_id'], unique=False)
    op.create_index(op.f('ix_favorite_routes_user_id'), 'favorite_routes', ['user_id'], unique=False)
    op.create_index('ix_favorite_routes_user_order', 'favorite_routes', ['user_id', 'display_order'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('stop_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category', sa.Enum('ATRASO', 'LOTACAO', 'SEGURANCA', 'MANUTENCAO', 'OUTRO', name='reportcategory', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', 'REJECTED', name='reportstatus', native_enum=False, length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_route_id'), 'reports', ['route_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_stop_id'), 'reports', ['stop_id'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('service_id', sa.String(length=50), nullable=False),
    sa.Column('trip_headsign', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Enum('PRIMARY_TO_SECONDARY', 'SECONDARY_TO_PRIMARY', name='tripdirection', native_enum=False), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_external_id'), 'trips', ['external_id'], unique=True)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_trips_service_id'), 'trips', ['service_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('modal', sa.Enum('BUS', 'METRO', 'TRAIN', name='transportmodal', native_enum=False, length=20), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('is_accessible', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('direction', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_external_id'), 'vehicles', ['external_id'], unique=True)
    op.create_index(op.f('ix_vehicles_last_seen_at'), 'vehicles', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_vehicles_modal'), 'vehicles', ['modal'], unique=False)
    op.create_index(op.f('ix_vehicles_route_id'), 'vehicles', ['route_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('stop_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('category', sa.Enum('LIMPEZA', 'PONTUALIDADE', 'SEGURANCA', 'CONFORTO', 'ATENDIMENTO', 'GERAL', name='ratingcategory', native_enum=False, length=50), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_created_at'), 'ratings', ['created_at'], unique=False)
    op.create_index(op.f('ix_ratings_route_id'), 'ratings', ['route_id'], unique=False)
    op.create_index(op.f('ix_ratings_stop_id'), 'ratings', ['stop_id'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('stop_predictions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stop_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('route_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('predicted_eta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stop_predictions_expires_at'), 'stop_predictions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_stop_predictions_predicted_eta'), 'stop_predictions', ['predicted_eta'], unique=False)
    op.create_index(op.f('ix_stop_predictions_route_id'), 'stop_predictions', ['route_id'], unique=False)
    op.create_index(op.f('ix_stop_predictions_stop_id'), 'stop_predictions', ['stop_id'], unique=False)
    op.create_index(op.f('ix_stop_predictions_vehicle_id'), 'stop_predictions', ['vehicle_id'], unique=False)
    op.create_table('vehicle_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('heading', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_positions_recorded_at'), 'vehicle_positions', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_vehicle_positions_vehicle_id'), 'vehicle_positions', ['vehicle_id'], unique=False)
    op.create_index('ix_vehicle_positions_vehicle_recorded', 'vehicle_positions', ['vehicle_id', 'recorded_at'], unique=False, postgresql_ops={'recorded_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_positions_vehicle_recorded', table_name='vehicle_positions', postgresql_ops={'recorded_at': 'DESC'})
    op.drop_index(op.f('ix_vehicle_positions_vehicle_id'), table_name='vehicle_positions')
    op.drop_index(op.f('ix_vehicle_positions_recorded_at'), table_name='vehicle_positions')
    op.drop_table('vehicle_positions')
    op.drop_index(op.f('ix_stop_predictions_vehicle_id'), table_name='stop_predictions')
    op.drop_index(op.f('ix_stop_predictions_stop_id'), table_name='stop_predictions')
    op.drop_index(op.f('ix_stop_predictions_route_id'), table_name='stop_predictions')
    op.drop_index(op.f('ix_stop_predictions_predicted_eta'), table_name='stop_predictions')
    op.drop_index(op.f('ix_stop_predictions_expires_at'), table_name='stop_predictions')
    op.drop_table('stop_predictions')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_stop_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_route_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_created_at'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_vehicles_route_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_modal'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_last_seen_at'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_external_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_trips_service_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_route_id'), table_name='trips')
    op.drop_index(op.f('ix_trips_external_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_stop_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_route_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_favorite_routes_user_order', table_name='favorite_routes')
    op.drop_index(op.f('ix_favorite_routes_user_id'), table_name='favorite_routes')
    op.drop_index(op.f('ix_favorite_routes_route_id'), table_name='favorite_routes')
    op.drop_index(op.f('ix_favorite_routes_created_at'), table_name='favorite_routes')
    op.drop_table('favorite_routes')
    op.drop_index(op.f('ix_stops_modal'), table_name='stops')
    op.drop_index(op.f('ix_stops_external_id'), table_name='stops')
    op.drop_table('stops')
    op.drop_index(op.f('ix_routes_modal'), table_name='routes')
    op.drop_index(op.f('ix_routes_external_id'), table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
